"""
Dataset generation orchestration.

Every scene is generated by a pure function of ``(scene spec, config)`` with
seeds derived from the master seed through ``numpy.random.SeedSequence``:

* scene      : SeedSequence(master_seed, spawn_key=(scene_id, 0))
* camera     : SeedSequence(master_seed, spawn_key=(scene_id, 1, camera_slot))
* condition  : SeedSequence(master_seed, spawn_key=(scene_id, 2, camera_slot, condition_id))

so the dataset is bit-for-bit reproducible regardless of the number of worker
processes.  Workers generate scenes in parallel; the main process writes HDF5.
"""
from __future__ import annotations

import json
import multiprocessing as mp
import time
from typing import Any, Dict, List

import numpy as np

from .cameras import project_points, sample_intrinsics
from .config import expand_conditions, scene_specs
from .noise import apply_condition, condition_attrs
from .poses import pose_matrix, sample_camera_pose
from .scenes import generate_scene
from .storage import DatasetWriter


def _seed_of(seq: np.random.SeedSequence) -> int:
    return int(seq.generate_state(1, dtype=np.uint32)[0])


def generate_scene_record(spec: Dict[str, Any], cfg: Dict[str, Any]) -> Dict[str, Any]:
    """Generate one scene with all its cameras and noise conditions (pure function)."""
    master = int(cfg["dataset"]["master_seed"])
    scene_id = int(spec["scene_id"])
    scene_seq = np.random.SeedSequence(master, spawn_key=(scene_id, 0))
    rng_scene = np.random.default_rng(scene_seq)
    scene = generate_scene(rng_scene, spec["scene_type"], cfg)

    cam_cfg = cfg["cameras"]
    pose_cfg = cfg["poses"]
    conditions = expand_conditions(cfg)
    min_visible = int(cam_cfg["min_visible_points"])
    min_depth = float(cam_cfg["min_depth"])
    max_attempts = int(cam_cfg["max_pose_attempts"])

    cameras: List[Dict[str, Any]] = []
    skipped = 0
    camera_slot = 0
    for intrinsics_id in range(int(cam_cfg["num_intrinsics_per_scene"])):
        intr_seq = np.random.SeedSequence(master, spawn_key=(scene_id, 3, intrinsics_id))
        intr = sample_intrinsics(np.random.default_rng(intr_seq), cam_cfg)
        for pose_id in range(int(cam_cfg["num_poses_per_intrinsics"])):
            cam_seq = np.random.SeedSequence(master, spawn_key=(scene_id, 1, camera_slot))
            rng_cam = np.random.default_rng(cam_seq)
            projection = None
            for attempt in range(max_attempts):
                R, t, C, info = sample_camera_pose(rng_cam, scene, intr, pose_cfg)
                proj = project_points(scene.points, intr, R, t, min_depth=min_depth)
                if proj.uv.shape[0] >= min_visible:
                    projection = (R, t, C, info, proj, attempt + 1)
                    break
            if projection is None:
                skipped += 1
                camera_slot += 1
                continue
            R, t, C, info, proj, attempts = projection
            attrs = intr.as_attrs()
            attrs.update({
                "intrinsics_id": intrinsics_id,
                "pose_id": pose_id,
                "seed": _seed_of(cam_seq),
                "pose_strategy": info["strategy"],
                "camera_distance": float(info["distance"]),
                "elevation_deg": float(info["elevation_deg"]),
                "roll_deg": float(info["roll_deg"]),
                "look_at_target": np.asarray(info["target"], dtype=np.float64),
                "pose_attempts": int(attempts),
            })
            cond_records = []
            for condition_id, cond in enumerate(conditions):
                cond_seq = np.random.SeedSequence(master, spawn_key=(scene_id, 2, camera_slot, condition_id))
                rng_cond = np.random.default_rng(cond_seq)
                uv, mask = apply_condition(rng_cond, proj.uv, cond, intr.width, intr.height)
                cattrs = condition_attrs(cond, mask)
                cattrs["seed"] = _seed_of(cond_seq)
                cond_records.append({
                    "condition_id": condition_id, "points_2d": uv, "outlier_mask": mask, "attrs": cattrs,
                })
            cameras.append({
                "camera_id": len(cameras),
                "K": intr.K.copy(),
                "dist_coeffs": intr.coeffs.copy(),
                "pose_Rt": pose_matrix(R, t),
                "camera_center": C,
                "points_2d_clean": proj.uv,
                "point_indices": proj.indices,
                "depths": proj.depth,
                "attrs": attrs,
                "conditions": cond_records,
            })
            camera_slot += 1

    return {
        "scene_id": scene_id,
        "scene_type": spec["scene_type"],
        "split": spec["split"],
        "seed": _seed_of(scene_seq),
        "points_3d": scene.points,
        "point_labels": scene.labels,
        "scene_attrs": scene.as_attrs(),
        "cameras": cameras,
        "num_cameras_skipped": skipped,
    }


def _worker(args):
    spec, cfg = args
    return generate_scene_record(spec, cfg)


def generate_dataset(cfg: Dict[str, Any], out_dir, workers: int = 1, progress: bool = True,
                     log=print) -> Dict[str, Any]:
    """Generate the full dataset described by ``cfg`` into ``out_dir``."""
    specs = scene_specs(cfg)
    writer = DatasetWriter(out_dir, cfg)
    t0 = time.time()
    n_total = len(specs)
    try:
        bar = None
        if progress:
            try:
                from tqdm import tqdm
                bar = tqdm(total=n_total, unit="scene", desc="generating", dynamic_ncols=True)
            except ImportError:  # pragma: no cover
                bar = None
        if workers is None or workers <= 1:
            iterator = (generate_scene_record(spec, cfg) for spec in specs)
            for rec in iterator:
                writer.write_scene(rec)
                if bar:
                    bar.update(1)
        else:
            ctx = mp.get_context("spawn")
            with ctx.Pool(processes=int(workers)) as pool:
                for rec in pool.imap(_worker, [(spec, cfg) for spec in specs], chunksize=1):
                    writer.write_scene(rec)
                    if bar:
                        bar.update(1)
        if bar:
            bar.close()
    finally:
        stats = writer.close()
    stats["generation_seconds"] = round(time.time() - t0, 2)
    stats["workers"] = int(workers or 1)
    with open(writer.meta_dir / "dataset_stats.json", "w", encoding="utf-8") as fh:
        json.dump(stats, fh, indent=2)
    if log:
        log(f"scenes: {stats['num_scenes']}  cameras: {stats['num_cameras']}  "
            f"samples: {stats['num_samples']}  correspondences: {stats['num_correspondences']:,}  "
            f"skipped cameras: {stats['num_cameras_skipped']}  "
            f"size: {stats['hdf5_bytes'] / 1e9:.3f} GB  time: {stats['generation_seconds']:.1f}s")
    return stats
